server:
  port: 5000

spring:
  application:
    name: eureka-zuul
  rabbitmq:
    host: 192.168.153.134
    port: 5672
    username: admin
    password: admin
    listener:
      direct:
        retry:
          enabled: true
      simple:
        retry:
          enabled: true
  zipkin:
    sender:
      type: rabbit
  #    base-url: http://localhsot:9411
  sleuth:
    sampler:
      #以100%的概率将链路的数据上传给ZIPkin Server,默认值为0.1
      probability: 1.0

eureka:
  client:
    service-url:
      defauleZone: http://eureka-server1:8761/eureka/,http://eureka-server2:8762/eureka/
zuul:
  routes:
    client:
      path: /client/**
      serviceId: eureka-client
    ribbonapi:
      path: /ribbonapi/**
      serviceId: eureka-ribbon-client
    feignapi:

      path: /feignapi/**
      serviceId: eureka-feign-client
        #匹配/github/直接重定向到https://github.com/
    github:
      path: /github/**
      url: https://github.com/
  sensitive-headers:
#feign:
#  hystrix:
#    enabled: true

