server:
  port: 5050

spring:
  application:
    name: zipkin-server
  main:
    allow-bean-definition-overriding: true

eureka:
  #  instance:
  #    hostname: localhost
  client:
    service-url:
      #      defauleZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
      defauleZone: http://eureka-server1:8761/eureka/,http://eureka-server2:8762/eureka/