server:
  port: 8082

spring:
  application:
    name: eureka-feign-client

eureka:
  instance:
    hostname: eureka-feign-client
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
