server:
  port: 8082

spring:
  application:
    name: eureka-feign-client
  rabbitmq:
    host: 192.168.153.134
    port: 5672
    username: admin
    password: admin
    listener:
      direct:
        retry:
          enabled: true
      simple:
        retry:
          enabled: true
  zipkin:
    sender:
      type: rabbit
#    base-url: http://localhost:9411
  sleuth:
    sampler:
      #应采样的请求的概率。 例如。 应该对1.0  -  100％的请求进行抽样。 精度仅为整数（即不支持0.1％的迹线）。
      probability: 1.0

eureka:
#  instance:
#    hostname: eureka-feign-client
  client:
    service-url:
#      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
      defaultZone: http://eureka-server1:8761/eureka/,http://eureka-server2:8762/eureka/

feign:
  hystrix:
    enabled: true
